package com.convenio.dal.entities;
// default package
// Generated 21-06-2016 07:09:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Cartera generated by hbm2java
 */
@Entity
@Table(name = "CARTERA")
public class Cartera implements java.io.Serializable {

	private int id;
	private int rut;
	private int ruttitular;
	private String nombre;
	private Boolean istitular;
	private Boolean isactivo;
	private Boolean isffaa;
	private Boolean iscarga;

	public Cartera() {
	}

	public Cartera(int id, int rut, int ruttitular) {
		this.id = id;
		this.rut = rut;
		this.ruttitular = ruttitular;
	}

	public Cartera(int id, int rut, int ruttitular, String nombre,
			Boolean istitular, Boolean isactivo, Boolean isffaa, Boolean iscarga) {
		this.id = id;
		this.rut = rut;
		this.ruttitular = ruttitular;
		this.nombre = nombre;
		this.istitular = istitular;
		this.isactivo = isactivo;
		this.isffaa = isffaa;
		this.iscarga = iscarga;
	}

	@Id
	@SequenceGenerator(name="SEQ_GEN", sequenceName="CARTERA_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "RUT", nullable = false, precision = 8, scale = 0)
	public int getRut() {
		return this.rut;
	}

	public void setRut(int rut) {
		this.rut = rut;
	}

	@Column(name = "RUTTITULAR", nullable = false, precision = 8, scale = 0)
	public int getRuttitular() {
		return this.ruttitular;
	}

	public void setRuttitular(int ruttitular) {
		this.ruttitular = ruttitular;
	}

	@Column(name = "NOMBRE", length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ISTITULAR", precision = 1, scale = 0)
	public Boolean getIstitular() {
		return this.istitular;
	}

	public void setIstitular(Boolean istitular) {
		this.istitular = istitular;
	}

	@Column(name = "ISACTIVO", precision = 1, scale = 0)
	public Boolean getIsactivo() {
		return this.isactivo;
	}

	public void setIsactivo(Boolean isactivo) {
		this.isactivo = isactivo;
	}

	@Column(name = "ISFFAA", precision = 1, scale = 0)
	public Boolean getIsffaa() {
		return this.isffaa;
	}

	public void setIsffaa(Boolean isffaa) {
		this.isffaa = isffaa;
	}

	@Column(name = "ISCARGA", precision = 1, scale = 0)
	public Boolean getIscarga() {
		return this.iscarga;
	}

	public void setIscarga(Boolean iscarga) {
		this.iscarga = iscarga;
	}

}
