package com.convenio.dal.entities;
// default package
// Generated 21-06-2016 07:09:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Condicionespecifica generated by hbm2java
 */
@Entity
@Table(name = "CONDICIONESPECIFICA")
public class Condicionespecifica implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set<PrestacionCondespecifica> prestacionCondespecificas = new HashSet<PrestacionCondespecifica>(
			0);

	public Condicionespecifica() {
	}

	public Condicionespecifica(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public Condicionespecifica(int id, String nombre,
			Set<PrestacionCondespecifica> prestacionCondespecificas) {
		this.id = id;
		this.nombre = nombre;
		this.prestacionCondespecificas = prestacionCondespecificas;
	}

	@Id
	@SequenceGenerator(name="SEQ_GEN", sequenceName="CONDICIONESPECIFICA_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "NOMBRE", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "condicionespecifica")
	public Set<PrestacionCondespecifica> getPrestacionCondespecificas() {
		return this.prestacionCondespecificas;
	}

	public void setPrestacionCondespecificas(
			Set<PrestacionCondespecifica> prestacionCondespecificas) {
		this.prestacionCondespecificas = prestacionCondespecificas;
	}

}
