package com.convenio.dal.entities;
// default package
// Generated 21-06-2016 07:09:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Condiciongeneral generated by hbm2java
 */
@Entity
@Table(name = "CONDICIONGENERAL")
public class Condiciongeneral implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set<PrestacionCondgeneral> prestacionCondgenerals = new HashSet<PrestacionCondgeneral>(
			0);

	public Condiciongeneral() {
	}

	public Condiciongeneral(int id) {
		this.id = id;
	}

	public Condiciongeneral(int id, String nombre,
			Set<PrestacionCondgeneral> prestacionCondgenerals) {
		this.id = id;
		this.nombre = nombre;
		this.prestacionCondgenerals = prestacionCondgenerals;
	}

	@Id
	@SequenceGenerator(name="SEQ_GEN", sequenceName="CONDICIONGENERAL_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "NOMBRE", length = 400)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "condiciongeneral")
	public Set<PrestacionCondgeneral> getPrestacionCondgenerals() {
		return this.prestacionCondgenerals;
	}

	public void setPrestacionCondgenerals(
			Set<PrestacionCondgeneral> prestacionCondgenerals) {
		this.prestacionCondgenerals = prestacionCondgenerals;
	}

}
