package com.convenio.dal.entities;
// default package
// Generated 21-06-2016 07:09:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Prestacion generated by hbm2java
 */
@Entity
@Table(name = "PRESTACION")
public class Prestacion implements java.io.Serializable {

	private int id;
	private String descripcion;
	private Set<PrestacionCondgeneral> prestacionCondgenerals = new HashSet<PrestacionCondgeneral>(
			0);
	private Set<PrestacionCondespecifica> prestacionCondespecificas = new HashSet<PrestacionCondespecifica>(
			0);
	private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

	public Prestacion() {
	}

	public Prestacion(int id) {
		this.id = id;
	}

	public Prestacion(int id, String descripcion,
			Set<PrestacionCondgeneral> prestacionCondgenerals,
			Set<PrestacionCondespecifica> prestacionCondespecificas,
			Set<Transaccion> transaccions) {
		this.id = id;
		this.descripcion = descripcion;
		this.prestacionCondgenerals = prestacionCondgenerals;
		this.prestacionCondespecificas = prestacionCondespecificas;
		this.transaccions = transaccions;
	}

	@Id
	@SequenceGenerator(name="SEQ_GEN", sequenceName="PRESTACION_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "DESCRIPCION", length = 400)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestacion")
	public Set<PrestacionCondgeneral> getPrestacionCondgenerals() {
		return this.prestacionCondgenerals;
	}

	public void setPrestacionCondgenerals(
			Set<PrestacionCondgeneral> prestacionCondgenerals) {
		this.prestacionCondgenerals = prestacionCondgenerals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestacion")
	public Set<PrestacionCondespecifica> getPrestacionCondespecificas() {
		return this.prestacionCondespecificas;
	}

	public void setPrestacionCondespecificas(
			Set<PrestacionCondespecifica> prestacionCondespecificas) {
		this.prestacionCondespecificas = prestacionCondespecificas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestacion")
	public Set<Transaccion> getTransaccions() {
		return this.transaccions;
	}

	public void setTransaccions(Set<Transaccion> transaccions) {
		this.transaccions = transaccions;
	}

}
