package com.convenio.dal.entities;
// default package
// Generated 21-06-2016 07:09:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PrestacionCondgeneral generated by hbm2java
 */
@Entity
@Table(name = "PRESTACION_CONDGENERAL")
public class PrestacionCondgeneral implements java.io.Serializable {

	private int id;
	private Prestacion prestacion;
	private Condiciongeneral condiciongeneral;

	public PrestacionCondgeneral() {
	}

	public PrestacionCondgeneral(int id, Prestacion prestacion,
			Condiciongeneral condiciongeneral) {
		this.id = id;
		this.prestacion = prestacion;
		this.condiciongeneral = condiciongeneral;
	}

	@Id
	@SequenceGenerator(name="SEQ_GEN", sequenceName="PRESTACION_CONDGENERAL_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PRESTACIONID", nullable = false)
	public Prestacion getPrestacion() {
		return this.prestacion;
	}

	public void setPrestacion(Prestacion prestacion) {
		this.prestacion = prestacion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CONDICIONGENERALID", nullable = false)
	public Condiciongeneral getCondiciongeneral() {
		return this.condiciongeneral;
	}

	public void setCondiciongeneral(Condiciongeneral condiciongeneral) {
		this.condiciongeneral = condiciongeneral;
	}

}
