package com.convenio.dal.entities;
// default package
// Generated 21-06-2016 07:09:07 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PrestacionCondespecifica generated by hbm2java
 */
@Entity
@Table(name = "PRESTACION_CONDESPECIFICA")
public class PrestacionCondespecifica implements java.io.Serializable {

	private int id;
	private Prestacion prestacion;
	private Condicionespecifica condicionespecifica;
	private int valor;

	public PrestacionCondespecifica() {
	}

	public PrestacionCondespecifica(int id, Prestacion prestacion,
			Condicionespecifica condicionespecifica, int valor) {
		this.id = id;
		this.prestacion = prestacion;
		this.condicionespecifica = condicionespecifica;
		this.valor = valor;
	}

	@Id
	@SequenceGenerator(name="SEQ_GEN", sequenceName="PRESTACION_CONDESPECIFI_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PRESTACIONID", nullable = false)
	public Prestacion getPrestacion() {
		return this.prestacion;
	}

	public void setPrestacion(Prestacion prestacion) {
		this.prestacion = prestacion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CONDICIONESPECIFICAID", nullable = false)
	public Condicionespecifica getCondicionespecifica() {
		return this.condicionespecifica;
	}

	public void setCondicionespecifica(Condicionespecifica condicionespecifica) {
		this.condicionespecifica = condicionespecifica;
	}

	@Column(name = "VALOR", nullable = false, precision = 8, scale = 0)
	public int getValor() {
		return this.valor;
	}

	public void setValor(int valor) {
		this.valor = valor;
	}

}
