package com.convenio.dal.entities;
// default package
// Generated 21-06-2016 07:09:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaccion generated by hbm2java
 */
@Entity
@Table(name = "TRANSACCION")
public class Transaccion implements java.io.Serializable {

	private int id;
	private Prestacion prestacion;
	private int ruttitular;
	private int rutbeneficiado;
	private Date fechaconsulta;
	private Date fecharegistra;
	private String prestacionXML;

	public Transaccion() {
	}

	public Transaccion(int id, Prestacion prestacion, int ruttitular,
			int rutbeneficiado, Date fechaconsulta, String prestacionXML) {
		this.id = id;
		this.prestacion = prestacion;
		this.ruttitular = ruttitular;
		this.rutbeneficiado = rutbeneficiado;
		this.fechaconsulta = fechaconsulta;
		this.prestacionXML = prestacionXML;
	}

	public Transaccion(int id, Prestacion prestacion, int ruttitular,
			int rutbeneficiado, Date fechaconsulta, Date fecharegistra,
			String prestacionXML) {
		this.id = id;
		this.prestacion = prestacion;
		this.ruttitular = ruttitular;
		this.rutbeneficiado = rutbeneficiado;
		this.fechaconsulta = fechaconsulta;
		this.fecharegistra = fecharegistra;
		this.prestacionXML = prestacionXML;
	}

	@Id
	@SequenceGenerator(name="SEQ_GEN", sequenceName="TRANSACCION_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRESTACIONID", nullable = false)
	public Prestacion getPrestacion() {
		return this.prestacion;
	}

	public void setPrestacion(Prestacion prestacion) {
		this.prestacion = prestacion;
	}

	@Column(name = "RUTTITULAR", nullable = false, precision = 8, scale = 0)
	public int getRuttitular() {
		return this.ruttitular;
	}

	public void setRuttitular(int ruttitular) {
		this.ruttitular = ruttitular;
	}

	@Column(name = "RUTBENEFICIADO", nullable = false, precision = 8, scale = 0)
	public int getRutbeneficiado() {
		return this.rutbeneficiado;
	}

	public void setRutbeneficiado(int rutbeneficiado) {
		this.rutbeneficiado = rutbeneficiado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHACONSULTA", nullable = false, length = 7)
	public Date getFechaconsulta() {
		return this.fechaconsulta;
	}

	public void setFechaconsulta(Date fechaconsulta) {
		this.fechaconsulta = fechaconsulta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHAREGISTRA", length = 7)
	public Date getFecharegistra() {
		return this.fecharegistra;
	}

	public void setFecharegistra(Date fecharegistra) {
		this.fecharegistra = fecharegistra;
	}

	@Column(name = "PRESTACION", nullable = false, length = 2000)
	public String getPrestacionXML() {
		return this.prestacionXML;
	}

	public void setPrestacionXML(String prestacionXML) {
		this.prestacionXML = prestacionXML;
	}

}
